import { Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { ScorecardResult } from "@ai-scorecard/core";

const styles = StyleSheet.create({
  page: {
    backgroundColor: "#0f172a",
    padding: 0,
    display: "flex",
    flexDirection: "column",
  },
  header: {
    backgroundColor: "#1e293b",
    padding: 48,
    paddingBottom: 32,
    borderBottomWidth: 4,
    borderBottomColor: "#6366f1",
  },
  badge: {
    fontSize: 10,
    color: "#94a3b8",
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  title: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#f8fafc",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 18,
    color: "#94a3b8",
  },
  body: {
    flex: 1,
    padding: 48,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 32,
  },
  infoRow: {
    marginBottom: 20,
  },
  label: {
    fontSize: 10,
    color: "#64748b",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  value: {
    fontSize: 20,
    color: "#f1f5f9",
    fontWeight: "bold",
  },
  scoreBox: {
    backgroundColor: "#1e293b",
    borderRadius: 12,
    padding: 32,
    marginTop: 16,
    display: "flex",
    flexDirection: "row",
    gap: 48,
  },
  scoreItem: {
    flex: 1,
  },
  scoreBig: {
    fontSize: 52,
    fontWeight: "bold",
    marginBottom: 4,
  },
  scoreLabel: {
    fontSize: 12,
    color: "#94a3b8",
  },
  tierLabel: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 4,
  },
  footer: {
    padding: 32,
    paddingTop: 0,
    borderTopWidth: 1,
    borderTopColor: "#1e293b",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontSize: 10,
    color: "#475569",
  },
});

const TIER_COLORS: Record<number, string> = {
  1: "#94a3b8",
  2: "#facc15",
  3: "#60a5fa",
  4: "#4ade80",
};

interface CoverPageProps {
  result: ScorecardResult;
}

export function CoverPage({ result }: CoverPageProps) {
  const tierColor = TIER_COLORS[result.tier.level] ?? "#f8fafc";
  const orgName = result.metadata.target;
  const date = new Date(result.assessedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.badge}>Confidential · AI Maturity Assessment</Text>
        <Text style={styles.title}>AI Adoption Scorecard</Text>
        <Text style={styles.subtitle}>Engineering Leadership Report</Text>
      </View>

      {/* Body */}
      <View style={styles.body}>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Organization</Text>
          <Text style={styles.value}>{orgName}</Text>
        </View>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Assessment Date</Text>
          <Text style={styles.value}>{date}</Text>
        </View>

        {/* Score Box */}
        <View style={styles.scoreBox}>
          <View style={styles.scoreItem}>
            <Text style={styles.label}>Overall Score</Text>
            <Text style={[styles.scoreBig, { color: tierColor }]}>
              {result.totalScore}
              <Text style={{ fontSize: 24, color: "#64748b" }}>
                /{result.maxScore}
              </Text>
            </Text>
            <Text style={styles.scoreLabel}>{result.percentage}% of maximum</Text>
          </View>
          <View style={styles.scoreItem}>
            <Text style={styles.label}>Maturity Tier</Text>
            <Text style={[styles.tierLabel, { color: tierColor }]}>
              Tier {result.tier.level}: {result.tier.label}
            </Text>
            <Text style={styles.scoreLabel}>
              {result.tier.minScore}–{result.tier.maxScore} point range
            </Text>
          </View>
        </View>
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>
          Generated by AI Scorecard · github.com/AngelCantugr/ai-scorecard
        </Text>
        <Text style={styles.footerText}>{date}</Text>
      </View>
    </Page>
  );
}
