import type { Octokit } from "@octokit/rest";
import type { SignalResult, Evidence } from "@ai-scorecard/core";
import type { RepoInfo } from "./repo-scan.js";

/** Known AI review bot login names */
const AI_REVIEW_BOTS = [
  "coderabbitai",
  "github-copilot",
  "copilot",
  "deepsource-autofix",
  "codeclimate-results",
  "sonarcloud",
  "snyk-bot",
  "dependabot",
];

/** Patterns indicating AI attribution in commits/PRs */
const AI_ATTRIBUTION_PATTERNS = [
  /co-authored-by:.*\b(copilot|claude|gpt|ai|bot)\b/i,
  /generated by (copilot|claude|chatgpt|openai|anthropic)/i,
  /\[ai\]|\[copilot\]|\[generated\]/i,
  /authored by ai/i,
];

/**
 * Fetch recent PRs for a repo (last 30 days).
 */
async function fetchRecentPRs(
  octokit: Octokit,
  owner: string,
  repo: string,
  since: Date
): Promise<
  {
    number: number;
    createdAt: Date;
    mergedAt: Date | null;
    title: string;
    body: string | null;
    reviews: { login: string | undefined; body: string }[];
    commits: { message: string; authorLogin: string | undefined }[];
  }[]
> {
  try {
    const { data: prs } = await octokit.pulls.list({
      owner,
      repo,
      state: "closed",
      sort: "updated",
      direction: "desc",
      per_page: 50,
    });

    const recentPRs = prs.filter((pr) => pr.merged_at !== null && new Date(pr.updated_at) >= since);

    // Sequential processing to avoid triggering GitHub secondary rate limits
    const enriched: {
      number: number;
      createdAt: Date;
      mergedAt: Date | null;
      title: string;
      body: string | null;
      reviews: { login: string | undefined; body: string }[];
      commits: { message: string; authorLogin: string | undefined }[];
    }[] = [];

    for (const pr of recentPRs.slice(0, 20)) {
      let reviews: { login: string | undefined; body: string }[] = [];
      let commits: { message: string; authorLogin: string | undefined }[] = [];

      try {
        const { data: reviewData } = await octokit.pulls.listReviews({
          owner,
          repo,
          pull_number: pr.number,
        });
        reviews = reviewData.map((r) => ({
          login: r.user?.login,
          body: r.body ?? "",
        }));
      } catch {
        // ignore
      }

      try {
        const { data: commitData } = await octokit.pulls.listCommits({
          owner,
          repo,
          pull_number: pr.number,
          per_page: 20,
        });
        commits = commitData.map((c) => ({
          message: c.commit.message,
          authorLogin: c.author?.login ?? undefined,
        }));
      } catch {
        // ignore
      }

      enriched.push({
        number: pr.number,
        createdAt: new Date(pr.created_at),
        mergedAt: pr.merged_at ? new Date(pr.merged_at) : null,
        title: pr.title,
        body: pr.body,
        reviews,
        commits,
      });
    }

    return enriched;
  } catch {
    return [];
  }
}

/**
 * Q13 — AI agent task percentage
 * Looks for bot commits and AI-generated PR labels.
 */
export async function collectAgentTaskPercentSignal(
  octokit: Octokit,
  repos: RepoInfo[]
): Promise<SignalResult> {
  const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  let totalPRs = 0;
  let aiAttributedPRs = 0;

  for (const repo of repos.slice(0, 10)) {
    const owner = repo.fullName.split("/")[0] ?? "";
    const prs = await fetchRecentPRs(octokit, owner, repo.name, since);
    totalPRs += prs.length;

    for (const pr of prs) {
      const hasAICommit = pr.commits.some((c) => {
        const msg = c.message.toLowerCase();
        return (
          AI_ATTRIBUTION_PATTERNS.some((p) => p.test(msg)) ||
          AI_REVIEW_BOTS.some((bot) => c.authorLogin?.toLowerCase() === bot)
        );
      });

      const hasAIBody =
        pr.body !== null && AI_ATTRIBUTION_PATTERNS.some((p) => p.test(pr.body ?? ""));

      if (hasAICommit || hasAIBody) {
        aiAttributedPRs++;
      }
    }
  }

  const percentage = totalPRs > 0 ? (aiAttributedPRs / totalPRs) * 100 : 0;

  const evidence: Evidence[] = [
    {
      source: "github:pulls",
      data: { totalPRs, aiAttributedPRs, percentage: Math.round(percentage) },
      summary: `${aiAttributedPRs}/${totalPRs} PRs (${Math.round(percentage)}%) appear AI-attributed in the last 30 days.`,
    },
  ];

  let score: 0 | 1 | 2 = 0;
  if (percentage > 30) score = 2;
  else if (percentage >= 5) score = 1;

  return {
    signalId: "github:pr-analytics:q13-agent-task-percent",
    questionId: "D2-Q13",
    score,
    evidence,
    confidence: 0.4,
  };
}

/**
 * Q16 — AI-powered code review
 * Looks for bot review comments on PRs.
 */
export async function collectAICodeReviewSignal(
  octokit: Octokit,
  repos: RepoInfo[]
): Promise<SignalResult> {
  const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  let totalReviews = 0;
  let botReviews = 0;
  const botNames = new Set<string>();

  for (const repo of repos.slice(0, 10)) {
    const owner = repo.fullName.split("/")[0] ?? "";
    const prs = await fetchRecentPRs(octokit, owner, repo.name, since);

    for (const pr of prs) {
      for (const review of pr.reviews) {
        totalReviews++;
        const login = review.login?.toLowerCase() ?? "";
        if (AI_REVIEW_BOTS.some((bot) => login.includes(bot))) {
          botReviews++;
          if (review.login) botNames.add(review.login);
        }
      }
    }
  }

  const evidence: Evidence[] = [
    {
      source: "github:pulls",
      data: { totalReviews, botReviews, botNames: Array.from(botNames) },
      summary:
        botReviews === 0
          ? "No AI/bot review comments found on recent PRs."
          : `${botReviews} bot reviews by: ${Array.from(botNames).join(", ")}`,
    },
  ];

  let score: 0 | 1 | 2 = 0;
  if (botReviews > 10) score = 2;
  else if (botReviews > 0) score = 1;

  return {
    signalId: "github:pr-analytics:q16-ai-code-review",
    questionId: "D3-Q16",
    score,
    evidence,
    confidence: 0.5,
  };
}

/**
 * Q18 — PR cycle time
 * Calculates median open→merge time over last 30 days.
 */
export async function collectPRCycleTimeSignal(
  octokit: Octokit,
  repos: RepoInfo[]
): Promise<SignalResult> {
  const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  const cycleTimes: number[] = [];

  for (const repo of repos.slice(0, 10)) {
    const owner = repo.fullName.split("/")[0] ?? "";
    const prs = await fetchRecentPRs(octokit, owner, repo.name, since);

    for (const pr of prs) {
      if (pr.mergedAt !== null) {
        const cycleTimeHours = (pr.mergedAt.getTime() - pr.createdAt.getTime()) / (1000 * 60 * 60);
        cycleTimes.push(cycleTimeHours);
      }
    }
  }

  let medianCycleHours: number | null = null;
  if (cycleTimes.length > 0) {
    cycleTimes.sort((a, b) => a - b);
    const mid = Math.floor(cycleTimes.length / 2);
    medianCycleHours =
      cycleTimes.length % 2 !== 0
        ? (cycleTimes[mid] ?? 0)
        : ((cycleTimes[mid - 1] ?? 0) + (cycleTimes[mid] ?? 0)) / 2;
  }

  const evidence: Evidence[] = [
    {
      source: "github:pulls",
      data: {
        totalMergedPRs: cycleTimes.length,
        medianCycleHours: medianCycleHours !== null ? Math.round(medianCycleHours) : null,
      },
      summary:
        medianCycleHours === null
          ? "No merged PRs found in last 30 days."
          : `Median PR cycle time: ${Math.round(medianCycleHours)} hours (${cycleTimes.length} PRs)`,
    },
  ];

  // Score: 0 = not measured, 1 = measured, 2 = measured and tracked (presence of data = measured)
  let score: 0 | 1 | 2 = 0;
  if (medianCycleHours !== null && cycleTimes.length >= 10) score = 2;
  else if (medianCycleHours !== null) score = 1;

  return {
    signalId: "github:pr-analytics:q18-pr-cycle-time",
    questionId: "D3-Q18",
    score,
    evidence,
    confidence: 0.8,
  };
}

/**
 * Q20 — AI artifact SDLC (AI configs reviewed via PRs)
 * Checks if AI config files have PR review history by listing merged PRs
 * and inspecting their changed files via pulls.listFiles.
 */
export async function collectAIArtifactSDLCSignal(
  octokit: Octokit,
  repos: RepoInfo[]
): Promise<SignalResult> {
  const since = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000); // 90 days
  const reviewedRepos: string[] = [];
  const unreviewedRepos: string[] = [];

  const aiConfigFilePatterns = /CLAUDE\.md|agents\.md|\.cursorrules|\.clinerules|prompts?\//i;

  for (const repo of repos.slice(0, 15)) {
    const owner = repo.fullName.split("/")[0] ?? "";
    try {
      // List recent merged PRs
      const { data: prs } = await octokit.pulls.list({
        owner,
        repo: repo.name,
        state: "closed",
        sort: "updated",
        direction: "desc",
        per_page: 20,
      });

      const mergedPRs = prs.filter(
        (pr) => pr.merged_at !== null && new Date(pr.merged_at) >= since
      );

      let foundReviewedPR = false;
      for (const pr of mergedPRs.slice(0, 10)) {
        try {
          const { data: files } = await octokit.pulls.listFiles({
            owner,
            repo: repo.name,
            pull_number: pr.number,
            per_page: 100,
          });
          const touchedAIConfig = files.some((f) => aiConfigFilePatterns.test(f.filename));
          if (touchedAIConfig) {
            foundReviewedPR = true;
            break;
          }
        } catch {
          // ignore per-PR failures
        }
      }

      // Also check commits on main branch that touch these files (direct pushes)
      const { data: commits } = await octokit.repos.listCommits({
        owner,
        repo: repo.name,
        since: since.toISOString(),
        per_page: 30,
      });
      const aiRelatedCommits = commits.filter((c) => aiConfigFilePatterns.test(c.commit.message));

      if (foundReviewedPR) {
        reviewedRepos.push(repo.fullName);
      } else if (aiRelatedCommits.length > 0) {
        unreviewedRepos.push(repo.fullName);
      }
    } catch {
      // ignore per-repo failures
    }
  }

  const evidence: Evidence[] = [
    {
      source: "github:pulls,commits",
      data: { reviewedRepos, unreviewedRepos },
      summary:
        reviewedRepos.length === 0 && unreviewedRepos.length === 0
          ? "No AI artifact changes found in recent history."
          : `AI artifacts reviewed via PR in: ${reviewedRepos.join(", ")}. Direct commits in: ${unreviewedRepos.join(", ")}`,
    },
  ];

  let score: 0 | 1 | 2 = 0;
  if (reviewedRepos.length >= 2) score = 2;
  else if (reviewedRepos.length >= 1 || unreviewedRepos.length >= 1) score = 1;

  return {
    signalId: "github:pr-analytics:q20-ai-artifact-sdlc",
    questionId: "D4-Q20",
    score,
    evidence,
    confidence: 0.5,
  };
}

/**
 * Q23 — AI attribution in commits/PRs
 */
export async function collectAIAttributionSignal(
  octokit: Octokit,
  repos: RepoInfo[]
): Promise<SignalResult> {
  const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  let totalCommits = 0;
  let attributedCommits = 0;

  for (const repo of repos.slice(0, 10)) {
    const owner = repo.fullName.split("/")[0] ?? "";
    try {
      const { data: commits } = await octokit.repos.listCommits({
        owner,
        repo: repo.name,
        since: since.toISOString(),
        per_page: 50,
      });

      totalCommits += commits.length;
      for (const commit of commits) {
        const msg = commit.commit.message;
        if (AI_ATTRIBUTION_PATTERNS.some((p) => p.test(msg))) {
          attributedCommits++;
        }
      }
    } catch {
      // ignore
    }
  }

  const percentage = totalCommits > 0 ? (attributedCommits / totalCommits) * 100 : 0;

  const evidence: Evidence[] = [
    {
      source: "github:commits",
      data: { totalCommits, attributedCommits, percentage: Math.round(percentage) },
      summary:
        attributedCommits === 0
          ? "No AI attribution patterns found in recent commits."
          : `${attributedCommits}/${totalCommits} commits (${Math.round(percentage)}%) have AI attribution.`,
    },
  ];

  let score: 0 | 1 | 2 = 0;
  if (attributedCommits >= 5 && percentage > 10) score = 2;
  else if (attributedCommits >= 1) score = 1;

  return {
    signalId: "github:pr-analytics:q23-ai-attribution",
    questionId: "D4-Q23",
    score,
    evidence,
    confidence: 0.6,
  };
}
